# Generated by Django 2.1.4 on 2018-12-10 03:11

import development_of_test_habits.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='HomeWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='development_of_test_habits.Class')),
            ],
        ),
        migrations.AddField(
            model_name='homework',
            name='student_id',
            field=models.ForeignKey(on_delete=development_of_test_habits.models.Student, to='development_of_test_habits.Student'),
        ),
        migrations.AddField(
            model_name='class',
            name='school_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='development_of_test_habits.School'),
        ),
    ]
