# Generated by Django 2.1.4 on 2018-12-04 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('make_good_use_of_migrations', '0002_init_book_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='remark',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
